---
title: "Extra Practice 1"
author:  | 
  | W. Evan Johnson, Ph.D.
  | Director, Center for Data Science
  | Rutgers New Jersey Medical School
date: "2023-03-13"
output: pdf_document
---
\subsection*{Advanced Unix Tools}
Most Unix implementations include a large number of powerful tools and utilities. (Unix has been in development for more than 50 years!). We were only able to scratch the surface in our class time. It will take time to become comfortable with Unix, but as you struggle, you will find yourself learning just by looking at \texttt{man} files and finding solutions on the internet. For this Extra Practice, you will explore several more advanced Unix functions. You can use any resource available to you--classmates, the internet, and Dr. Johnson. Ask all the questions you want, just make sure you do the work and you learn! 

\begin{enumerate}
	\item Learn about the \texttt{tar} function. What is a tarball? How is it different from a .zip file? Download the EP1.tar.gz file from GitHub and unzip the contents, and report that code you used. How effective is the compression for this tarball? After you complete Question \ref{cbball}, add the basketball data to the directory and generate a gzipped tarball for all the EP1 data (plus the basketball data) and provide the code you used. 
	\item  \label{cbball} Learn more about tools for downloading files from external servers (e.g., \texttt{scp}, \texttt{ftp}, \texttt{sftp}, \texttt{rsync}), and for to downloading data from webpages (e.g., \texttt{curl}, \texttt{wget}, \texttt{mget}). Use an appropriate function to download the scores for all college basketball games for the 2021-2022 season (\href{http://kenpom.com/cbbga22.txt}{http://kenpom.com/cbbga22.txt}). Give the code you used to download these data. 
	\item Research the \texttt{chmod} function. Give short explanation of what this function does, its syntax, and examples when you would use it. Practice \texttt{chmod} by changing the permissions on the `TB\_microbiome\_data.txt' file in the EP1 directory from the previous questions. Give examples of the code you used and show that the code works (e.g., use \texttt{ls -l}). 
	\item  The \texttt{grep} function is an extremely powerful tool for search (potentially large) files for patterns and strings. One advantage is that you don't have to open the file to conduct a search! Using the internet, find a short tutorial on the basics of \texttt{grep}, and give the code and results for the following tasks: 
		\begin{enumerate}
		\item How many games has Rutgers played so far this season? (hint: search for `Rutgers' in the file)
		\item How many games have been played by teams other than Rutgers? (i.e., inverse search)
		\item What was the score when Rutgers played Michigan? How many games had Rutgers played before that game? (i.e., add line numbers to the result)
		\item How many coronavirus genomes are present in the `viral.fasta' file? How many of these are SARS-COV-2?  
		\item How many times does the letter `A' (capital or lowercase) appear in all the files from the EP1 tar file plus the college basketball data? (i.e., ignore case).
		\item What {\it Staphylococcus} species are present in the `TB\_microbiome\_data.txt' file? (hint: each separate microbe has its own row in the file). Print out the counts for {\it Mycobacterium tuberculosis}. How many {\it Streptococcus} species are present? 
		\end{enumerate}
	\item Learn how to use \texttt{less} to display large text files in the terminal using the \texttt{man} help page. Using the ``OPTIONS" section of the \texttt{man} page, open the `virus.fa' file to display so that it does not wrap long lines (default), displays line numbers, and opens at the first occurrence of `coronavirus'. Provide the command you used to open the file in this way. Within \texttt{less}, learn and practice how to scroll forward/backward, scroll forward/backward $n$ lines, jump to the middle or end of the file, and search for text in the document. When would it be advantageous to use \texttt{less} over a tool like Microsoft Word? Ask Dr. Johnson why in Unix \texttt{more} is less and \texttt{less} is more :-). 
	\item Open a text file in \texttt{vim} and change the file. How do you How do you move the the beginning/end of a line, insert text, copy and paste, delete text and lines? How do you save your file or exit \texttt{vim} with/without saving your result? What are the advantages and disadvantages of \texttt{vim} versus \texttt{less}? In which scenarios would you use each of these? 
	\item Learn about \texttt{pipes} and \texttt{redirects} in Unix. In which scenarios would you use them, and why are they helpful? describe what the following commands do: 
	\begin{enumerate}
		\item \texttt{ls -l | less}
		\item \texttt{ls -l > directory\_contents.txt}
		\item \texttt{ls -l >> directory\_contents.txt}
		\item \texttt{cat directory\_contents.txt | head -3 | tail -2}
		\item \texttt{ls | grep -c html}
		\item \texttt{ls | wc -l}
		\item \texttt{cat file1.txt file2.txt > file3.txt}
	\end{enumerate}
	You can also us pipes in R! Investigate how to do this and give the code for a great example. 
	
	\item Learn about another Unix command that we have not discussed. Give a short description of this function, when you would use it, its syntax, and give some examples of its use.
	\item {\bf Wait to to complete the following two tasks for the Git and GitHub lecture:} 
	\begin{enumerate}
		\item Fork the \href{https://github.com/wevanjohnson/my.package}{https://github.com/wevanjohnson/my.package} directory and clone it to your local machine. Then add your name as an author in the DESCRIPTION file local repository and add a multiplication function to the R package (R folder). Then push the changes to your GitHub fork, and send me a pull request with your changes.  
		\item Set up a git repository for this extra practice on your computer (repo named ``DataScienceLectures"), add files/changes to it, and upload it to GitHub. This is how you will post your EP results for this lecture series! (including this one!). 
	\end{enumerate}. 

\end{enumerate}


